# source("best.R")

some_vector <- c('MUSC MEDICAL CENTER',
  'LAKE CITY COMMUNITY HOSPITAL',
  
  'MCLEOD MEDICAL CENTER - DARLINGTON',
  
  'MARY BLACK MEMORIAL HOSPITAL',
  
  'GRAND STRAND REG MED CENTER',
  
  'CAROLINAS HOSPITAL SYSTEM'
)

q2 <- c(

'KINGSBROOK JEWISH MEDICAL CENTER',

'CROUSE HOSPITAL',

'MAIMONIDES MEDICAL CENTER',

'BROOKS MEMORIAL HOSPITAL',

'NORTHERN DUTCHESS HOSPITAL',

'HOSPITAL FOR SPECIAL SURGERY'


)